#!/bin/bash

ARGS="--param ../Labs/rmi-2425/C3straight-config.xml"
ARGS+=" --lab ../Labs/rmi-2425/C3straight-lab.xml"
ARGS+=" --grid ../Labs/rmi-2425/C3straight-grid.xml"
ARGS+=" --scoring 3"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect)

killall simulator

echo Bye
