#!/bin/bash

ARGS="--param ../Labs/rmi-2425/C1v2-config.xml"
ARGS+=" --lab ../Labs/rmi-2425/C1v2-lab.xml"
ARGS+=" --grid ../Labs/rmi-2425/C1v2-grid.xml"
ARGS+=" --scoring 1"
(cd simulator; ./simulator $ARGS) &

sleep 2

(cd Viewer; ./Viewer --autoconnect)

killall simulator

echo Bye
